<a href="https://colab.research.google.com/github/jayoung977/DM2020/blob/master/1203_%EB%82%98%EC%9D%B4%EB%B8%8C%EB%B2%A0%EC%9D%B4%EC%A7%80%EC%95%8801.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [29]:
tennis_data = pd.read_csv('/content/drive/My Drive/데이터마이닝/PlayTennis.csv')
tennis_data

Outlook Temperature Humidity    Wind PlayTennis
0      Sunny         Hot     High    Weak         No
1      Sunny         Hot     High  Strong         No
2   Overcast         Hot     High    Weak        Yes
3       Rain        Mild     High    Weak        Yes
4       Rain        Cool   Normal    Weak        Yes
5       Rain        Cool   Normal  Strong         No
6   Overcast        Cool   Normal  Strong        Yes
7      Sunny        Mild     High    Weak         No
8      Sunny        Cool   Normal    Weak        Yes
9       Rain        Mild   Normal    Weak        Yes
10     Sunny        Mild   Normal  Strong        Yes
11  Overcast        Mild     High  Strong        Yes
12  Overcast         Hot   Normal    Weak        Yes
13      Rain        Mild     High  Strong         No

In [30]:
tennis_data.Outlook = tennis_data.Outlook.replace('Sunny',0)
tennis_data.Outlook = tennis_data.Outlook.replace('Overcast', 1)
tennis_data.Outlook = tennis_data.Outlook.replace('Rain',2)

tennis_data.Temperature = tennis_data.Temperature.replace('Hot',3)
tennis_data.Temperature = tennis_data.Temperature.replace('Mild',4)
tennis_data.Temperature = tennis_data.Temperature.replace('Cool',5)

tennis_data.Humidity = tennis_data.Humidity.replace('High',6)
tennis_data.Humidity = tennis_data.Humidity.replace('Normal',7)

tennis_data.Wind = tennis_data.Wind.replace('Weak',8)
tennis_data.Wind = tennis_data.Wind.replace('Strong',9)

tennis_data.PlayTennis = tennis_data.PlayTennis.replace('No',10)
tennis_data.PlayTennis = tennis_data.PlayTennis.replace('Yes',11)

tennis_data

Outlook  Temperature  Humidity  Wind  PlayTennis
0         0            3         6     8          10
1         0            3         6     9          10
2         1            3         6     8          11
3         2            4         6     8          11
4         2            5         7     8          11
5         2            5         7     9          10
6         1            5         7     9          11
7         0            4         6     8          10
8         0            5         7     8          11
9         2            4         7     8          11
10        0            4         7     9          11
11        1            4         6     9          11
12        1            3         7     8          11
13        2            4         6     9          10

In [31]:
X = np.array(pd.DataFrame(tennis_data, columns=['Outlook','Temperature', 'Humidity', 'Wind']))

In [32]:
y = np.array(pd.DataFrame(tennis_data, columns=['PlayTennis']))

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 2,random_state=42)

In [34]:
X_train

array([[0, 3, 6, 8],
       [1, 3, 7, 8],
       [2, 5, 7, 9],
       [0, 5, 7, 8],
       [1, 3, 6, 8],
       [0, 3, 6, 9],
       [2, 4, 6, 9],
       [2, 5, 7, 8],
       [0, 4, 6, 8],
       [0, 4, 7, 9],
       [2, 4, 6, 8],
       [1, 5, 7, 9]])

In [35]:
X_test

array([[2, 4, 7, 8],
       [1, 4, 6, 9]])

In [36]:
y_train

array([[10],
       [11],
       [10],
       [11],
       [11],
       [10],
       [10],
       [11],
       [10],
       [11],
       [11],
       [11]])

In [37]:
y_test

array([[11],
       [11]])

In [38]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train.ravel())

GaussianNB(priors=None, var_smoothing=1e-09)

In [39]:
y_pred= model.predict(X_test) 
print("Predicted Value:", y_pred)

Predicted Value: [11 10]


In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.5